// 꿈의 장르와 꿈의 느낌, 색상을 정의한 상수
const COLORS = {
  red: { hex: "#DE6F73" },
  orange: { hex: "#DEA78B" },
  yellow: { hex: "#FFF7AE" },
  green: { hex: "#B4DA9E" },
  blue: { hex: "#B5E9F3" },
  navy: { hex: "#B1B6E3" },
  purple: { hex: "#8C6AAC", textColor: "white" },
  lavender: { hex: "#D599CA" },
  pink: { hex: "#F6C9D5" },
  stone: { hex: "#9DB5A8" },
  gray: { hex: "#CCCCCC" },
  black: { hex: "#646464", textColor: "white" },
};

const DREAM_GENRES = [
  { id: "adventure", text: "모험", color: COLORS.orange },
  { id: "military", text: "재입대", color: COLORS.stone },
  { id: "travel", text: "여행", color: COLORS.blue },
  { id: "crime", text: "범죄", color: COLORS.black },
  { id: "daily", text: "일상", color: COLORS.green },
  { id: "romance", text: "로맨스", color: COLORS.pink },
  { id: "fantasy", text: "판타지", color: COLORS.purple },
  { id: "animals", text: "동물", color: COLORS.green },
  { id: "superpower", text: "초능력", color: COLORS.navy },
  { id: "war", text: "전쟁", color: COLORS.red },
  { id: "apocalypse", text: "아포칼립스", color: COLORS.black },
  { id: "disaster", text: "재난", color: COLORS.red },
  { id: "scifi", text: "SF", color: COLORS.blue },
  { id: "food", text: "먹방", color: COLORS.orange },
  { id: "sports", text: "스포츠", color: COLORS.yellow },
  { id: "movie", text: "영화", color: COLORS.purple },
  { id: "school", text: "학교", color: COLORS.stone },
  { id: "schoolLife", text: "학교생활", color: COLORS.stone },
  { id: "lecture", text: "강좌", color: COLORS.gray },
  { id: "past", text: "과거", color: COLORS.lavender },
  { id: "timeLoop", text: "타임루프", color: COLORS.purple },
  { id: "friendship", text: "우정", color: COLORS.yellow },
  { id: "cars", text: "자동차", color: COLORS.red },
  { id: "survival", text: "살아남기", color: COLORS.stone },
  { id: "politics", text: "정치", color: COLORS.navy },
  { id: "family", text: "가족", color: COLORS.green },
  { id: "medical", text: "의학", color: COLORS.blue },
  { id: "gaming", text: "게임", color: COLORS.purple },
  { id: "music", text: "음악", color: COLORS.lavender },
  { id: "thriller", text: "스릴러", color: COLORS.black },
  { id: "horror", text: "공포", color: COLORS.black },
  { id: "company", text: "회사", color: COLORS.gray },
];

const DREAM_MOODS = [
  { id: "fun", text: "재밌음", color: COLORS.yellow },
  { id: "boring", text: "재미없음", color: COLORS.gray },
  { id: "scary", text: "공포", color: COLORS.black },
  { id: "complicated", text: "난해", color: COLORS.purple },
  { id: "wishReality", text: "현실이었으면", color: COLORS.blue },
  { id: "gladDream", text: "꿈이라 다행", color: COLORS.green },
  { id: "touching", text: "감동", color: COLORS.pink },
  { id: "calm", text: "차분함", color: COLORS.stone },
  { id: "happy", text: "행복", color: COLORS.yellow },
  { id: "difficult", text: "힘들다", color: COLORS.gray },
  { id: "sad", text: "슬프다", color: COLORS.blue },
  { id: "normal", text: "보통", color: COLORS.stone },
  { id: "cute", text: "귀여움", color: COLORS.pink },
  { id: "cruel", text: "잔인", color: COLORS.red },
  { id: "thoughtless", text: "아무생각없음", color: COLORS.gray },
  { id: "fearful", text: "무서움", color: COLORS.black },
  { id: "unfair", text: "억울", color: COLORS.purple },
  { id: "confused", text: "혼란스러움", color: COLORS.navy },
  { id: "angry", text: "화남", color: COLORS.red },
  { id: "shy", text: "부끄러움", color: COLORS.lavender },
  { id: "kind", text: "친절함", color: COLORS.green },
];

export { DREAM_GENRES, DREAM_MOODS };
