// 꿈의 장르와 꿈의 느낌을 정의한 상수
const DREAM_GENRES = [
  { id: "adventure", text: "모험" },
  { id: "military", text: "재입대" },
  { id: "travel", text: "여행" },
  { id: "crime", text: "범죄" },
  { id: "daily", text: "일상" },
  { id: "romance", text: "로맨스" },
  { id: "fantasy", text: "판타지" },
  { id: "animals", text: "동물" },
  { id: "superpower", text: "초능력" },
  { id: "war", text: "전쟁" },
  { id: "apocalypse", text: "아포칼립스" },
  { id: "disaster", text: "재난" },
  { id: "scifi", text: "SF" },
  { id: "food", text: "먹방" },
  { id: "sports", text: "스포츠" },
  { id: "movie", text: "영화" },
  { id: "school", text: "학교" },
  { id: "schoolLife", text: "학교생활" },
  { id: "lecture", text: "강좌" },
  { id: "past", text: "과거" },
  { id: "timeLoop", text: "타임루프" },
  { id: "friendship", text: "우정" },
  { id: "cars", text: "자동차" },
  { id: "survival", text: "살아남기" },
  { id: "politics", text: "정치" },
  { id: "family", text: "가족" },
  { id: "medical", text: "의학" },
  { id: "gaming", text: "게임" },
  { id: "music", text: "음악" },
  { id: "thriller", text: "스릴러" },
  { id: "horror", text: "공포" },
  { id: "company", text: "회사" },
];

const DREAM_MOODS = [
  { id: "fun", text: "재밌음" },
  { id: "boring", text: "재미없음" },
  { id: "scary", text: "공포" },
  { id: "complicated", text: "난해" },
  { id: "wishReality", text: "현실이었으면" },
  { id: "gladDream", text: "꿈이라 다행" },
  { id: "touching", text: "감동" },
  { id: "calm", text: "차분함" },
  { id: "happy", text: "행복" },
  { id: "difficult", text: "힘들다" },
  { id: "sad", text: "슬프다" },
  { id: "normal", text: "보통" },
  { id: "cute", text: "귀여움" },
  { id: "cruel", text: "잔인" },
  { id: "thoughtless", text: "아무생각없음" },
  { id: "fearful", text: "무서움" },
  { id: "unfair", text: "억울" },
  { id: "confused", text: "혼란스러움" },
  { id: "angry", text: "화남" },
  { id: "shy", text: "부끄러움" },
  { id: "kind", text: "친절함" },
];

export { DREAM_GENRES, DREAM_MOODS };
