// 꿈의 장르와 꿈의 느낌, 색상을 정의한 상수
const COLORS = {
  light: {
    red: { hex: "#DE6F73" },
    orange: { hex: "#DEA78B" },
    yellow: { hex: "#FFF7AE" },
    green: { hex: "#B4DA9E" },
    blue: { hex: "#B5E9F3" },
    navy: { hex: "#B1B6E3" },
    purple: { hex: "#8C6AAC", textColor: "#fff" },
    lavender: { hex: "#D599CA" },
    pink: { hex: "#F6C9D5" },
    stone: { hex: "#9DB5A8" },
    gray: { hex: "#CCC" },
    black: { hex: "#646464", textColor: "#fff" },
  },
  dark: {
    red: { hex: "#7B4F51", textColor: "#eef0de" },
    orange: { hex: "#927162", textColor: "#eef0de" },
    yellow: { hex: "#A29868", textColor: "#eef0de" },
    green: { hex: "#7D9272", textColor: "#eef0de" },
    blue: { hex: "#536867", textColor: "#eef0de" },
    navy: { hex: "#606379", textColor: "#eef0de" },
    purple: { hex: "#503C64", textColor: "#eef0de" },
    lavender: { hex: "#7B5A75", textColor: "#eef0de" },
    pink: { hex: "#948186", textColor: "#eef0de" },
    stone: { hex: "#51645A", textColor: "#eef0de" },
    gray: { hex: "#797979", textColor: "#eef0de" },
    black: { hex: "#3A3A3A", textColor: "#eef0de" },
  },
};

const DREAM_GENRES = [
  {
    id: "adventure",
    text: "모험",
    lightColor: COLORS.light.orange,
    darkColor: COLORS.dark.orange,
  },
  {
    id: "military",
    text: "재입대",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "travel",
    text: "여행",
    lightColor: COLORS.light.blue,
    darkColor: COLORS.dark.blue,
  },
  {
    id: "crime",
    text: "범죄",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "daily",
    text: "일상",
    lightColor: COLORS.light.green,
    darkColor: COLORS.dark.green,
  },
  {
    id: "romance",
    text: "로맨스",
    lightColor: COLORS.light.pink,
    darkColor: COLORS.dark.pink,
  },
  {
    id: "fantasy",
    text: "판타지",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "animals",
    text: "동물",
    lightColor: COLORS.light.green,
    darkColor: COLORS.dark.green,
  },
  {
    id: "superpower",
    text: "초능력",
    lightColor: COLORS.light.navy,
    darkColor: COLORS.dark.navy,
  },
  {
    id: "war",
    text: "전쟁",
    lightColor: COLORS.light.red,
    darkColor: COLORS.dark.red,
  },
  {
    id: "apocalypse",
    text: "아포칼립스",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "disaster",
    text: "재난",
    lightColor: COLORS.light.red,
    darkColor: COLORS.dark.red,
  },
  {
    id: "scifi",
    text: "SF",
    lightColor: COLORS.light.blue,
    darkColor: COLORS.dark.blue,
  },
  {
    id: "food",
    text: "먹방",
    lightColor: COLORS.light.orange,
    darkColor: COLORS.dark.orange,
  },
  {
    id: "sports",
    text: "스포츠",
    lightColor: COLORS.light.yellow,
    darkColor: COLORS.dark.yellow,
  },
  {
    id: "movie",
    text: "영화",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "school",
    text: "학교",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "schoolLife",
    text: "학교생활",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "lecture",
    text: "강좌",
    lightColor: COLORS.light.gray,
    darkColor: COLORS.dark.gray,
  },
  {
    id: "past",
    text: "과거",
    lightColor: COLORS.light.lavender,
    darkColor: COLORS.dark.lavender,
  },
  {
    id: "timeLoop",
    text: "타임루프",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "friendship",
    text: "우정",
    lightColor: COLORS.light.yellow,
    darkColor: COLORS.dark.yellow,
  },
  {
    id: "cars",
    text: "자동차",
    lightColor: COLORS.light.red,
    darkColor: COLORS.dark.red,
  },
  {
    id: "survival",
    text: "살아남기",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "politics",
    text: "정치",
    lightColor: COLORS.light.navy,
    darkColor: COLORS.dark.navy,
  },
  {
    id: "family",
    text: "가족",
    lightColor: COLORS.light.green,
    darkColor: COLORS.dark.green,
  },
  {
    id: "medical",
    text: "의학",
    lightColor: COLORS.light.blue,
    darkColor: COLORS.dark.blue,
  },
  {
    id: "gaming",
    text: "게임",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "music",
    text: "음악",
    lightColor: COLORS.light.lavender,
    darkColor: COLORS.dark.lavender,
  },
  {
    id: "thriller",
    text: "스릴러",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "horror",
    text: "공포",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "company",
    text: "회사",
    lightColor: COLORS.light.gray,
    darkColor: COLORS.dark.gray,
  },
];

const DREAM_MOODS = [
  {
    id: "fun",
    text: "재밌음",
    lightColor: COLORS.light.yellow,
    darkColor: COLORS.dark.yellow,
  },
  {
    id: "boring",
    text: "재미없음",
    lightColor: COLORS.light.gray,
    darkColor: COLORS.dark.gray,
  },
  {
    id: "scary",
    text: "공포",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "complicated",
    text: "난해",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "wishReality",
    text: "현실이었으면",
    lightColor: COLORS.light.blue,
    darkColor: COLORS.dark.blue,
  },
  {
    id: "gladDream",
    text: "꿈이라 다행",
    lightColor: COLORS.light.green,
    darkColor: COLORS.dark.green,
  },
  {
    id: "touching",
    text: "감동",
    lightColor: COLORS.light.pink,
    darkColor: COLORS.dark.pink,
  },
  {
    id: "calm",
    text: "차분함",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "happy",
    text: "행복",
    lightColor: COLORS.light.yellow,
    darkColor: COLORS.dark.yellow,
  },
  {
    id: "difficult",
    text: "힘들다",
    lightColor: COLORS.light.gray,
    darkColor: COLORS.dark.gray,
  },
  {
    id: "sad",
    text: "슬프다",
    lightColor: COLORS.light.blue,
    darkColor: COLORS.dark.blue,
  },
  {
    id: "normal",
    text: "보통",
    lightColor: COLORS.light.stone,
    darkColor: COLORS.dark.stone,
  },
  {
    id: "cute",
    text: "귀여움",
    lightColor: COLORS.light.pink,
    darkColor: COLORS.dark.pink,
  },
  {
    id: "cruel",
    text: "잔인",
    lightColor: COLORS.light.red,
    darkColor: COLORS.dark.red,
  },
  {
    id: "thoughtless",
    text: "아무생각없음",
    lightColor: COLORS.light.gray,
    darkColor: COLORS.dark.gray,
  },
  {
    id: "fearful",
    text: "무서움",
    lightColor: COLORS.light.black,
    darkColor: COLORS.dark.black,
  },
  {
    id: "unfair",
    text: "억울",
    lightColor: COLORS.light.purple,
    darkColor: COLORS.dark.purple,
  },
  {
    id: "confused",
    text: "혼란스러움",
    lightColor: COLORS.light.navy,
    darkColor: COLORS.dark.navy,
  },
  {
    id: "angry",
    text: "화남",
    lightColor: COLORS.light.red,
    darkColor: COLORS.dark.red,
  },
  {
    id: "shy",
    text: "부끄러움",
    lightColor: COLORS.light.lavender,
    darkColor: COLORS.dark.lavender,
  },
  {
    id: "kind",
    text: "친절함",
    lightColor: COLORS.light.green,
    darkColor: COLORS.dark.green,
  },
];

export { DREAM_GENRES, DREAM_MOODS };
